# Project information
site_name: Material-for-MkDocs
# defeine TOC or order of website-
nav:
  - Home: index.md
  - Page - 2.md

site_author: Umesh Chauhan
site_description: >-
  DESCRIPTION
# Repository
repo_name: umeshchau/Material-for-MkDocs
repo_url: https://github.com/umeshchau/Material-for-MkDocs

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/umeshchau
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/UmeshCh94
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/umesh-chauhan-6b02b2236
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/nirvaan_umesh?igshid=YmJhNjkzNzY=

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2023 <a href="https://github.com/umeshchau"  target="_blank" rel="noopener">Umesh Chauhan</a>
